#
# cloudbuild.yaml
#
# Instructions for Google Cloud Build on how to build our builder.
#
# Usage:
#   $ gcloud builds submit . --config=cloudbuild.yaml
#
# Note: When Scala 2.13 becomes official, we'll either just move to it (cache the latest version only), or keep
#   both 2.12 and 2.13 around, for a while. This is merely a caching policy, so no need to mark it in the name.
#   Also, no need to mark JVM used, since it's only for compilation.
#
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=SBT_VERSION=1.2.7'
  - '--build-arg=SHA=1e81909fe2ba931684263fa58e9710e41ab50fe66bb0c20d274036db42caa70e'
  - '--tag=gcr.io/$PROJECT_ID/sbt-scala:1.2.7'
  - '.'

# Tag the default 'latest' version
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'gcr.io/$PROJECT_ID/sbt-scala:1.2.7'
  - 'gcr.io/$PROJECT_ID/sbt-scala'

images:
- 'gcr.io/$PROJECT_ID/sbt-scala'
- 'gcr.io/$PROJECT_ID/sbt-scala:1.2.7'
