#
# cloudbuild.yaml
#
# We want to provide both the versioned image and a non-versioned tag to it. This seems to need a YAML file, instead
# of simply using the Dockerfile.
#
# i.e. 'gcloud builds submit' (Google Cloud SDK 227) does not process multiple '-t' parameters but only the last one
#     (otherwise we could tag the builder there).
#
# Usage:
#   $ gcloud builds submit .
#
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=SBT_VER=1.2.8'
      - '--build-arg=SBT_SHA=f4b9fde91482705a772384c9ba6cdbb84d1c4f7a278fd2bfb34961cd9ed8e1d7'
      - '--tag=eu.gcr.io/$PROJECT_ID/sbt-scala:1.2.8-jdk8'
      - '--tag=eu.gcr.io/$PROJECT_ID/sbt-scala'
      - '.'
images:
  - 'eu.gcr.io/$PROJECT_ID/sbt-scala:1.2.8-jdk8'
  - 'eu.gcr.io/$PROJECT_ID/sbt-scala'
